### ISSUE TITLE
Bear

### ISSUE THREAD

**Issue by chaseoes** [bendem/HexChatAddons#4]
https://github.com/bendem/HexChatAddons/blob/master/addons/bear.py

![image](https://cloud.githubusercontent.com/assets/1302312/5925709/c501a742-a622-11e4-80b3-daef24fd8e21.png)

**Comment by chaseoes** [comment]
only YOU can say bear the right way

**Comment by chaseoes** [comment]
:trollface:

**Comment by bendem** [comment]
Actions will be taken to prevent wildfires, thanks for the report!
